/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetfood.gui;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import planetfood.dbutil.DBConnection;
import planetfood.pojo.UserProfile;

/**
 *
 * @author Shahnaz
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    
  
    public AdminOptionFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
        lblUserName.setText("Hello "+UserProfile.getUsername());
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jrbAddEmp = new javax.swing.JRadioButton();
        jrbViewEmp = new javax.swing.JRadioButton();
        jrbEditEmp = new javax.swing.JRadioButton();
        jrbRemoveEmp = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jrbRegisterCashier = new javax.swing.JRadioButton();
        jrbRemoveCashier = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jrbViewOrders = new javax.swing.JRadioButton();
        jrbViewDateWise = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jrbAddCategory = new javax.swing.JRadioButton();
        jrbEditCategory = new javax.swing.JRadioButton();
        jrbViewCategory = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jrbAddProduct = new javax.swing.JRadioButton();
        jrbViewProduct = new javax.swing.JRadioButton();
        jrbEditProduct = new javax.swing.JRadioButton();
        jrbRemoveProduct = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planet Food App");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        lblLogout.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLANET FOOD ADMIN PANEL");

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emp Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbAddEmp.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbAddEmp);
        jrbAddEmp.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddEmp.setText("Add Emp");

        jrbViewEmp.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbViewEmp);
        jrbViewEmp.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbViewEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewEmp.setText("View Emp");

        jrbEditEmp.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbEditEmp);
        jrbEditEmp.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbEditEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditEmp.setText("Edit Emp");

        jrbRemoveEmp.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbRemoveEmp);
        jrbRemoveEmp.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbRemoveEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbRemoveEmp.setText("Remove Emp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbRemoveEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbViewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbEditEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jrbAddEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbViewEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbEditEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbRemoveEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cashier Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbRegisterCashier.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbRegisterCashier);
        jrbRegisterCashier.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbRegisterCashier.setForeground(new java.awt.Color(255, 255, 255));
        jrbRegisterCashier.setText("Register Cashier");

        jrbRemoveCashier.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbRemoveCashier);
        jrbRemoveCashier.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbRemoveCashier.setForeground(new java.awt.Color(255, 255, 255));
        jrbRemoveCashier.setText("Remove Cashier");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbRemoveCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbRegisterCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jrbRegisterCashier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbRemoveCashier)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbViewOrders.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbViewOrders);
        jrbViewOrders.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewOrders.setText("View Orders");

        jrbViewDateWise.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbViewDateWise);
        jrbViewDateWise.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbViewDateWise.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewDateWise.setText("View Datewise");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbViewDateWise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbViewOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbViewDateWise)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbAddCategory.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbAddCategory);
        jrbAddCategory.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbAddCategory.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddCategory.setText("Add Category");

        jrbEditCategory.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbEditCategory);
        jrbEditCategory.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbEditCategory.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditCategory.setText("Edit Category");

        jrbViewCategory.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbViewCategory);
        jrbViewCategory.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbViewCategory.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewCategory.setText("View Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbViewCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbAddCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbEditCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jrbAddCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbEditCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbViewCategory)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbAddProduct.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbAddProduct);
        jrbAddProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddProduct.setText("Add Product");

        jrbViewProduct.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbViewProduct);
        jrbViewProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbViewProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewProduct.setText("View Product");
        jrbViewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbViewProductActionPerformed(evt);
            }
        });

        jrbEditProduct.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbEditProduct);
        jrbEditProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbEditProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditProduct.setText("Edit Product");

        jrbRemoveProduct.setBackground(new java.awt.Color(90, 0, 0));
        buttonGroup1.add(jrbRemoveProduct);
        jrbRemoveProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jrbRemoveProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbRemoveProduct.setText("Remove Product");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbRemoveProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jrbAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbViewProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbEditProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(jrbRemoveProduct)
                .addContainerGap())
        );

        btnDoTask.setBackground(new java.awt.Color(51, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(51, 0, 0));
        btnQuit.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Planet Food App\\image\\admin.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        jPanel7.setBackground(new java.awt.Color(90, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make A Choice");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoTask)
                    .addComponent(btnQuit))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbViewProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbViewProductActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked

        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered

        lblLogout.setForeground(Color.yellow);
        Font f=new Font("Tahoma",Font.BOLD,12);
        lblLogout.setFont(f);
        
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited

          lblLogout.setForeground(Color.white);
        Font f=new Font("Tahoma",Font.ITALIC,12);
        lblLogout.setFont(f);
        
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed

        String task=getOption();
              if(task==null)
              {
                  JOptionPane.showMessageDialog(null,"Please Choose an Option","ERROR!",JOptionPane.ERROR_MESSAGE);
                  return;
              }
              
            JFrame jf;
            if(task.equals("Add Emp"))
              {
                  jf=new AddEmpFrame();
                  jf.setVisible(true);
              }
             
              else if(task.equals("View Emp"))
              {
                  jf=new ViewEmpFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("Edit Emp"))
              {
                  jf=new EditEmpFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("Remove Emp"))
              {
            try {
                jf=new RemoveEmpFrame();
                jf.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AdminOptionFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
              }
             
            else  if(task.equals("Register Cashier"))
              {
                  jf=new RegisterCashierFrame();
                  jf.setVisible(true);
              }
             
              else if(task.equals("Remove Cashier"))
              {
                  jf=new RemoveCashierFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("View Orders"))
              {
                  jf=new ViewOrderFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("View Datewise"))
              {
                  jf=new ViewAllDateOrdersFrame();
                     jf.setVisible(true); 
              }
              else if(task.equals("Add Category"))
              {
                  jf=new AddCategoryFrame();
                  jf.setVisible(true);
              }
             
              else if(task.equals("Edit Category"))
              {
                  jf=new EditCategoryFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("View Category"))
              {
                  jf=new ViewAllCategoriesFrame();
                  jf.setVisible(true);
              }
            
              else if(task.equals("Add Product"))
              {
                  jf=new AddProductFrame();
                  jf.setVisible(true);
              }
             
              else if(task.equals("Add Product"))
              {
                  jf=new ViewProductsFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("Edit Product"))
              {
                  jf=new EditProductFrame();
                  jf.setVisible(true);
              }
              else if(task.equals("View Product"))
              {
                  jf=new ViewProductsFrame();
                  jf.setVisible(true);
              }
              
              else if(task.equals("Remove Product"))
              {
                  jf=new RemoveProductFrame();
                     jf.setVisible(true); 
              }
                           
           this.dispose();
              
              
        
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed

            int ans;
        ans=JOptionPane.showConfirmDialog(null,"Are you Sure You Want To Quitting ?","Quitting",
                JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(ans==JOptionPane.YES_NO_OPTION)
        {
            DBConnection.closeConnection();
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jrbAddCategory;
    private javax.swing.JRadioButton jrbAddEmp;
    private javax.swing.JRadioButton jrbAddProduct;
    private javax.swing.JRadioButton jrbEditCategory;
    private javax.swing.JRadioButton jrbEditEmp;
    private javax.swing.JRadioButton jrbEditProduct;
    private javax.swing.JRadioButton jrbRegisterCashier;
    private javax.swing.JRadioButton jrbRemoveCashier;
    private javax.swing.JRadioButton jrbRemoveEmp;
    private javax.swing.JRadioButton jrbRemoveProduct;
    private javax.swing.JRadioButton jrbViewCategory;
    private javax.swing.JRadioButton jrbViewDateWise;
    private javax.swing.JRadioButton jrbViewEmp;
    private javax.swing.JRadioButton jrbViewOrders;
    private javax.swing.JRadioButton jrbViewProduct;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables

    private String getOption() {
     
        if(jrbAddEmp.isSelected())
        {
            return jrbAddEmp.getText();
        }
        else if(jrbViewEmp.isSelected())
        {
            return jrbViewEmp.getText();
        }
        else if(jrbEditEmp.isSelected())
        {
            return(jrbEditEmp.getText());
        }
        else if(jrbRemoveEmp.isSelected())
        {
            return jrbRemoveEmp.getText();
        }
        else if(jrbRegisterCashier.isSelected())
        {
            return jrbRegisterCashier.getText();
        }
        else if(jrbRemoveCashier.isSelected())
        {
            return jrbRemoveCashier.getText();
        }
        else if(jrbViewOrders.isSelected())
        {
            return jrbViewOrders.getText();
        }
        else if(jrbViewDateWise.isSelected())
        {
            return jrbViewDateWise.getText();
        }
        else if(jrbAddCategory.isSelected())
        {
            return jrbAddCategory.getText();
        }
        else if(jrbEditCategory.isSelected())
        {
            return(jrbEditCategory.getText());
        }
        else if(jrbViewCategory.isSelected())
        {
            return jrbViewCategory.getText();
        }
        else if(jrbAddProduct.isSelected())
        {
            return jrbAddProduct.getText();
        }
        else if(jrbEditProduct.isSelected())
        {
            return jrbEditProduct.getText();
        }
        else if(jrbViewProduct.isSelected())
        {
            return jrbViewProduct.getText();
        }
        else if(jrbRemoveProduct.isSelected())
        {
            return jrbRemoveProduct.getText();
        }
        else
        {
            return null;
        }
    }
}
